### ISSUE TITLE
tranpose optimization for hardswish in tensorflow-lite

### ISSUE THREAD

**Issue by Xiadalei** [onnx/tensorflow-onnx#1816]
**Describe the bug**
When convering a tensorflow lite model with hardswish, specifically `TFL_HARD_SWISH` operator. There's tranpose wrapper around the hardswish operator.
> before conversion
![图片](https://user-images.githubusercontent.com/16681099/148363939-f969e953-def7-450b-91ad-b10603064131.png)

> after conversion
![图片](https://user-images.githubusercontent.com/16681099/148364001-57e8533a-655c-4f94-a182-b937aaac7cc2.png)

**Urgency**
none

**System information**
- OS Platform and Distribution: Linux Ubuntu 20.04
- Tensorflow Version: 2.6.0
- Python version: 3.8.10

**To Reproduce**

Just use offical mobileV3 model or use the model below
[v3-small_224_1.0_float.tflite.zip](https://github.com/onnx/tensorflow-onnx/files/7805224/v3-small_224_1.0_float.tflite.zip)

And the model converted is 
[v3.zip](https://github.com/onnx/tensorflow-onnx/files/7820912/v3.zip)

**Comment by hwangdeyu** [comment]
I don't find the same shape `Conv2d` op with the model graph you provide. Could you also check the model and send the repro conversion code?

**Comment by Xiadalei** [comment]
> I don't find the same shape `Conv2d` op with the model graph you provide. Could you also check the model and send the repro conversion code?

Sorry for the confusion that the pic was not from the model I uploaded. Now the question is fixed with model I converted.
also the conversion is conducted in cli with command like `python -m tf2onnx.convert --tflite ./v3-small_224_1.0_float.tflite --inputs-as-nchw input --opset 14 --output ./v3.onnx`

**Comment by hwangdeyu** [comment]
> > I don't find the same shape `Conv2d` op with the model graph you provide. Could you also check the model and send the repro conversion code?
> 
> Sorry for the confusion that the pic was not from the model I uploaded. Now the question is fixed with model I converted. Also the conversion is conducted in cli with command like `python -m tf2onnx.convert --tflite ./v3-small_224_1.0_float.tflite --inputs-as-nchw input --opset 14 --output ./v3.onnx`

Thanks, I closed this issue cause the question is fixed.

**Comment by Xiadalei** [comment]
> > > I don't find the same shape `Conv2d` op with the model graph you provide. Could you also check the model and send the repro conversion code?
> > 
> > 
> > Sorry for the confusion that the pic was not from the model I uploaded. Now the question is fixed with model I converted. Also the conversion is conducted in cli with command like `python -m tf2onnx.convert --tflite ./v3-small_224_1.0_float.tflite --inputs-as-nchw input --opset 14 --output ./v3.onnx`
> 
> Thanks, I closed this issue cause the question is fixed.

The fixed problem I refered to is not using the same model. The problem with tranposing still exists.
