### ISSUE TITLE
ConvTranspose missing auto_pad flag.

### ISSUE THREAD

**Issue by axeldavy** [onnx/tensorflow-onnx#765]
**Describe the bug**
Models using ConvTranspose operations in ONNX a stride > 1 and output_shape have a different output running with tensorflow or with tensorrt using onnx.
Running the onnx with tensorflow gives the error:

> tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
>   (0) Invalid argument: Conv2DSlowBackpropInput: Size of out_backprop doesn't match computed: actual = 40, computed = 39 spatial_dim: 2 input: 80 filter: 4 output: 40 stride: 2 dilation: 1
>          [[node conv2d_transpose (defined at /home/axel/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
>   (1) Invalid argument: Conv2DSlowBackpropInput: Size of out_backprop doesn't match computed: actual = 40, computed = 39 spatial_dim: 2 input: 80 filter: 4 output: 40 stride: 2 dilation: 1
>          [[node conv2d_transpose (defined at /home/axel/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
>          [[model_2/conv2d_2/Sigmoid/_11]]

**Urgency**
None

**System information**
- OS Platform and Distribution: Ubuntu 18.04
- Tensorflow Version: 1.15.0
- Python version: 3.6

My analysis of the issue is that in this particular scenario there is a missing auto_pad flag for the ConvTranpose operation. Setting it properly fixed the onnx for both tensorrt and tensorflow.

I will soon submit a PR with a proposed fix, but I decided to open this bug report for tracking.

**Comment by jignparm** [comment]
@axeldavy , can you post something similar to [this short example](https://github.com/onnx/tensorflow-onnx/blob/master/tests/test_backend.py#L2914) with the appropriate values, to illustrate when the failure occurs?

**Comment by axeldavy** [comment]
I don't understand how these tests work.

I see the only two tests of tf.nn.conv2d_transpose are with 'VALID'.
Maybe the bug would trigger with identical tests but with 'SAME'.

**Comment by jignparm** [comment]
The tests create a simple TF model, based on the TensorFlow API statements in that test, and pass in sample input data via a feed dictionary (e.g. _INPUT, _INPUT1 etc. in the example below). The output is collected from the TF model  (e.g. _OUTPUT). The TF model is then converted to an ONNX model, and the same input data is supplied for scoring. The output of the ONNX model is finally compared to the output of the TF model to ensure that is matches exactly.

If there is a case of Conv2DBackpropInput that cannot be converted correctly to ONNX (e.g. stride =1 or 2 etc.), there should be some simple parameters that will cause the outputs of the TF and ONNX models to differ (hence break the test). This would give a minimalist reproduction of the failure that needs to be fixed. 

```py
self._run_test_case([_OUTPUT], {_INPUT: input_sizes_val, _INPUT1: filters_val, _INPUT2: out_backprop_val})
```

To run the tests, do the following:

### Install PyTest and OnnxRuntime 

* pip install pytest onnxruntime

If you are missing other packages, the full suite is below

* pip install pytest onnxruntime  pytest-cov pytest-runner coverage graphviz requests pyyaml pillow pandas parameterized nbval

### Run PyTest

* set PYTHONPATH=d:\tf2onnx  _(replace tf2onnx with the root of of the code base on your host)_
* cd d:\tf2onnx
* pytest -k conv2d -v

### Example log
```
platform win32 -- Python 3.7.3, pytest-5.2.2, py-1.8.0, pluggy-0.13.0 -- d:\anaconda37\python.exe
cachedir: .pytest_cache
rootdir: D:\tf2onnx, inifile: setup.cfg
plugins: nbval-0.9.4, cov-2.8.1
collected 468 items / 455 deselected / 13 selected

tests/test_backend.py::BackendTests::test_conv2d_1 PASSED                                                            [  7%]
tests/test_backend.py::BackendTests::test_conv2d_2 PASSED                                                            [ 15%]
tests/test_backend.py::BackendTests::test_conv2d_3 PASSED                                                            [ 23%]
tests/test_backend.py::BackendTests::test_conv2d_4 PASSED                                                            [ 30%]
tests/test_backend.py::BackendTests::test_conv2d_5 PASSED                                                            [ 38%]
tests/test_backend.py::BackendTests::test_conv2d_6 PASSED                                                            [ 46%]
tests/test_backend.py::BackendTests::test_conv2d_7 PASSED                                                            [ 53%]
tests/test_backend.py::BackendTests::test_conv2d_8 PASSED                                                            [ 61%]
tests/test_backend.py::BackendTests::test_conv2d_transpose PASSED                                                    [ 69%]
tests/test_backend.py::BackendTests::test_conv2d_transpose2 PASSED                                                   [ 76%]
tests/test_backend.py::BackendTests::test_conv2d_with_input_transpose PASSED                                         [ 84%]
tests/test_backend.py::BackendTests::test_conv2d_with_pad PASSED                                                     [ 92%]
tests/test_graph.py::Tf2OnnxGraphTests::test_conv2d PASSED                                                           [100%]
```

**Comment by axeldavy** [comment]
Simply duplicating test_conv2d_tranpose with SAME instead of VALID seems to trigger the error.

**Comment by axeldavy** [comment]
So, to sum up my previous findings, I don't see a way to make a test that fails for this configuration.

The fix is probably to insert in Conv2DBackpropInput:
```
        if padding and padding.s.decode("utf-8") == 'SAME':
                node.set_attr("auto_pad", "SAME_LOWER")
            else:
                node.set_attr("auto_pad", "NOTSET")
                node.set_attr("pads", [0, 0, 0, 0])
```
This code works with Tensorrt, but it could also be that SAME_LOWER should be SAME_UPPER, I don't have the knowledge to decide which is correct.

**Comment by jignparm** [comment]
@axeldavy, closing this since there does not seem to be a way to reproduce this error. However, there was a similar bug in  test_conv2d_with_pad()  which was fixed instead.

Please reopen this if needed -- a sample failing unit test would be great.

**Comment by axeldavy** [comment]
Just for info, the conversion bug is still there with tf2onnx 1.6.3 and tensorflow 2.3.0, and my fix still helps it work seemingly correctly.
