### ISSUE TITLE
Flatten equations for rnn patterns

### ISSUE THREAD

**Issue by buddhapuneeth** [onnx/tensorflow-onnx#861]
In rnn_utils.py file, we can see all the regex of the LSTM and GRU nodes. It will be helpful if you add the actual mathematical equation also there as everyone follow different notations, so it will be more readable.

**Comment by buddhapuneeth** [comment]
Also we have operator type 'Enter' in the pattern, explanation of that operator is not available anywhere.

**Comment by jignparm** [comment]
These op patterns are what are observed in TF graphs, with  'Enter' and 'Exit' denoting flow-control operators. Most of the patterns in rnn_utils.py should read like a textbook (e.g. see below for a sequence of ConcatV2, MatMul, BiasAdd etc.). As for mathematical equations, that could be a nice touch, although that could apply to almost every other (regular) operator as well.

Is there some model that's not working/converting? 
```python
# TensorFlow LSTMCell/BasicLSTMCell computation graph matching
xc_pattern = OpTypePattern('Split', inputs=[
    OpTypePattern("Const"), # axis for split
    OpTypePattern("BiasAdd", name="bias_add", inputs=[
        OpTypePattern("MatMul", inputs=[
            OpTypePattern("ConcatV2|Concat", name="xh"),
            OpTypePattern("Enter", inputs=[
                OpTypePattern("*", name="cell_kernel"),
            ]),
        ]),
        OpTypePattern("Enter", inputs=[
            OpTypePattern("*", name="cell_bias"),
        ]),
    ]),
])

```

**Comment by buddhapuneeth** [comment]
Thanks for explaining on Enter and Exit operators.
Yes, I am facing issue while converting LSTM models. The sub-graph pattern matching is failing. 
It was working after making small change as below (by skipping Enter):
  ```python
xc_pattern = OpTypePattern('Split', inputs=[
    OpTypePattern("Const"), # axis for split
    OpTypePattern("BiasAdd", name="bias_add", inputs=[
        OpTypePattern("MatMul", inputs=[
            OpTypePattern("ConcatV2|Concat", name="xh"),
            OpTypePattern("*", name="cell_kernel"),
        ]),
        OpTypePattern("*", name="cell_bias"),
    ]),
])
```

This is working but need to understand why Enter operator is not coming.

**Comment by guschmue** [comment]
It basically matches the lowered tensorflow control flow and transforms it to something higher so we can map it to onnx ops like lstm or loop. Since this is part of the tensorflow graph it should be documented there but while ops like Enter are documented the concept itself is best explained here: https://arxiv.org/pdf/1805.01772.pdf

I don't think you can remove the Enter from the pattern since Enter indicates the start of the control flow. Maybe another op behind the Enter prevents the matching to work? 
Which tensorflow version are you using ?

**Comment by buddhapuneeth** [comment]
I am using TF 1.15.0 version. I am sure that after removing Enter, graph pattern is matching with LSTM.

**Comment by guschmue** [comment]
We definitely had issues with tf-1.15 and made changes in the master to get unit tests to work on it.
With the Enter removed, are you end to end results correct ?
We think we have unit test coverage for the common lstm's here https://github.com/onnx/tensorflow-onnx/blob/master/tests/test_lstm.py  and they are happy on tf-1.15, Anything special for your lstm?

**Comment by buddhapuneeth** [comment]
With Enter removed, it is working for us. I made comparison by running the generated onnx file on onnx runtime and pb file on tf runtime, results in both the cases are same.
I feel test cases for LSTM are buggy, as we are not checking for LSTM nodes in the resultant output graph. It is commented:
https://github.com/onnx/tensorflow-onnx/blob/master/tests/common.py#L329

When I debug, I am getting 0 LSTM nodes for those tests. 
Is there any recommended TF version for tf2onnx?

**Comment by guschmue** [comment]
oh, I see - we just execute the ops? I can take a look at it.
tf-1.14 is good, In tf-1.15 bunch of stuff has changed, guess because it is the bridge to tf-2.0.

**Comment by buddhapuneeth** [comment]
Yes. Assertion is not done in unit tests. 
I tried with tf-1.14, these are my observations:
  - LSTM Unit tests are passing (locally verifying the number of nodes)
  - Working without any change in xc_pattern (I mean with Enter operator)
So it is evident that there are some issues with tf-1.15. Unfortunately, we need to work on tf-1.15. Any suggested workarounds in this case?

**Comment by guschmue** [comment]
I need to find some time to debug it, should be getting to it this week.

**Comment by buddhapuneeth** [comment]
@guschmue I just want to check is there any update? or any tentative timeline for complete TF-1.15 support?

**Comment by guschmue** [comment]
I kind of know where the issue comes from. Trying to find time to fixing it but need to finish some other task first.

**Comment by buddhapuneeth** [comment]
Thanks @guschmue for the update.
Please update me once it is done. We have some version dependencies, it will be a great help.

**Comment by buddhapuneeth** [comment]
@guschmue any update on this.

**Comment by RandySheriffH** [comment]
I am working on a fix, will update thread shortly.

**Comment by RandySheriffH** [comment]
Here is my branch to fix LSTM pattern matching for tf >= 1.15.0 and < 2.x.
https://github.com/RandySheriffH/tensorflow-onnx/tree/rashuai/FixLSTM

**Comment by buddhapuneeth** [comment]
@RandySheriffH thanks for fix.

**Comment by RandySheriffH** [comment]
@buddhapuneeth:
Fix merged, does it work for your case?

**Comment by buddhapuneeth** [comment]
@RandySheriffH 
I checked my model on the latest master but I still have the same issue with TF 1.15.2.
With TF 1.14, it is working fine.
To make it work in TF 1.15.2, I did below change:
```
  xc_pattern = OpTypePattern('Split', inputs=[
  OpTypePattern("Const"), # axis for split
  OpTypePattern("BiasAdd", name="bias_add", inputs=[
      OpTypePattern("MatMul", inputs=[
          OpTypePattern("ConcatV2|Concat", name="xh"),
          OpTypePattern("*", name="cell_kernel"),
      ]),
      OpTypePattern("*", name="cell_bias"),
  ]),
])
```
 **I removed pattern matching for 'Enter'** then it is working fine. I am not able to find the root cause. 
 Unfortunately I can't share my model. But here are my findings:
- I created simple LSTM model which is working in both TF 1.14 and TF 1.15.2:
   You can see 'Enter' ---> 'Const' as input to 'BiasAdd/Identity'. 
<img width="920" alt="working" src="https://user-images.githubusercontent.com/3439010/81514546-a06e3f80-92e4-11ea-9ac3-2634642ec463.png">
 - In my model, it is different. Enter operator directly linked to 'BiasAdd'. But still LSTM pattern is working in TF 1.14.
<img width="447" alt="Failure" src="https://user-images.githubusercontent.com/3439010/81514604-e925f880-92e4-11ea-90df-ad11effa7966.png">

I am trying to understanding more on the control flows. But as of now I am still learning. Any inputs from you will help me.

Env: TF 1.15.2 (pip install), tensorflow-onnx (latest master), Py 36 (conda)

**Comment by RandySheriffH** [comment]
@buddhapuneeth : so your model graph (the one with Enter as direct input of BiasAdd) is from tf 1.15, right?

**Comment by buddhapuneeth** [comment]
@RandySheriffH I am not sure in which version that model was generated. The screenshots are from the saved model (.pb file). While converting to ONNX, as I mentioned earlier it is working with TF 1.14 not TF 1.15. 

I can backtrack the TF version used for model creation if you need.
But for the test model (first screenshot), I used TF 1.15 for creation.

One thing I am not able to understand is why same LSTM pattern is working for TF 1.14 not for TF 1.15 on ONNX side? I believe it should be independent of model creation.

**Comment by RandySheriffH** [comment]
@buddhapuneeth: with netron you should be able to tell the tf version - just click on one model input, right panel should show up to tell the detail. We could easily add your fix to the master there is zero proper UT since the "Enter->BiasAdd" pattern is no where to be found on our side.

**Comment by buddhapuneeth** [comment]
@RandySheriffH I am not able to find the TF version from the netron. 
<img width="887" alt="Screen Shot 2020-05-12 at 2 01 26 PM" src="https://user-images.githubusercontent.com/3439010/81745146-1dbac100-9459-11ea-8823-31f46cb7ea17.png">

**Comment by RandySheriffH** [comment]
@buddhapuneeth : that's ok, thanks for checking it and share the info.
I'd say currently let's stick to tf.1.14 which works for u, like being said - indeed we could add the pattern into master but it is not a typical case with verifiable test case.

**Comment by buddhapuneeth** [comment]
As model is generated in TF 1.13 and verifying on TF 1.15 caused this issue.
As it is stable on TF 1.14, closing this issue.
